### ISSUE TITLE
Error Starting Docker Container

### ISSUE THREAD

**Issue by alexblickenstaff** [ryankennedyio/ib-docker#2]
Thanks for making this, I'm really looking forward to using it!

I downloaded the files, built the docker image, modified the `docker-compose.yml` file to point to my locale docker image, and ran `docker-compose up` but got the following error:

Error: TWS version 959 is not installed: can't find /root/Jts/959/jars

Do I need to download and supply the TWS code myself somehow?

**Comment by ryankennedyio** [comment]
Hey Alex,

I've just rebuilt the image from scratch to test it, and everything seems fine. It might be an error in your `docker-compose.yml` file.

Could you copy and paste your modified file here for me to see? Obviously leave out the credentials

**Comment by alexblickenstaff** [comment]
Thanks for the fast response!

Sure, here it is:

```
tws:
  image: my-ib
  ports:
    - "4003:4003"
    - "5900:5900"
  volumes:
    - ./IBController.ini:/root/IBController/IBController.ini
    - ./jts.ini:/root/Jts/jts.ini
  environment:
    - TZ=Australia/Adelaide
    # Variables pulled from /IBController/IBControllerGatewayStart.sh
    - VNC_PASSWORD=password
    - TWS_MAJOR_VRSN=959
    - IBC_INI=/root/IBController/IBController.ini
    - TRADING_MODE=
    - IBC_PATH=/opt/IBController
    - TWS_PATH=/root/Jts
    - TWS_CONFIG_PATH=/root/Jts
    - LOG_PATH=/opt/IBController/Logs
    - TWSUSERID=edemo
    - TWSPASSWORD=demouser
    - FIXUSERID=
    - FIXPASSWORD=
    - JAVA_PATH=
    - APP=GATEWAY
```

The only thing I changed was the image name. This is the full log I got after `docker-compose up`:

```
tws_1 |
tws_1 | +==============================================================================
tws_1 | +
tws_1 | + IBController version 3.2.0
tws_1 | +
tws_1 | + Running GATEWAY 959
tws_1 | +
tws_1 | + Diagnostic information is logged in:
tws_1 | +
tws_1 | + /opt/IBController/Logs/ibc-3.2.0_GATEWAY-959_Wednesday.txt
tws_1 | +
tws_1 | +
tws_1 |
tws_1 | +==============================================================================
tws_1 | +
tws_1 | +                       **** An error has occurred ****
tws_1 | +
tws_1 | +                     Please look in the diagnostics file
tws_1 | +                   mentioned above for further information
tws_1 | +
tws_1 | +==============================================================================
tws_1 |
tws_1 | --pw = ***
tws_1 | --fix-user =
tws_1 | --fix-pw =
tws_1 |
tws_1 |
tws_1 | =========================== An error has occurred =============================
tws_1 |
tws_1 |
tws_1 |
tws_1 | Error: TWS version 959 is not installed: can't find /root/Jts/959/jars
```
